openapi: 3.0.0
info:
  title: test
  version: '1.0'
  description: test
  contact:
    name: API Support
    url: 'https://api.peachvideo.com/support'
    email: api.support@peachvideo.com
servers:
  - url: 'http://localhost:3000'
tags:
  - name: Account
    description: Account api collection
  - name: Campaign
    description: Campaign api collection
paths:
  /accounts:
    get:
      summary: Retrieve a list of accounts
      tags:
        - Account
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
              examples:
                example-listaccounts:
                  value:
                    - id: 1920
                      name: Peach Demo UK
                    - id: 1921
                      name: Peach Demo Germany
          headers: {}
      operationId: get-accounts
      description: retrieve a list of accounts
      security:
        - API Key - 1: []
  '/campaign/{campaignId}':
    get:
      summary: Retrieve campaign by an identifier
      tags:
        - Campaign
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Campaign'
      operationId: get-campaign
      description: Retrieve a specific campaign by an identifier
      security:
        - API Key - 1: []
    parameters:
      - schema:
          type: integer
          format: int64
          minimum: 1
        name: campaignId
        in: path
        description: Campaign identifier
        required: true
components:
  schemas:
    Account:
      title: Account
      type: object
      x-examples:
        example-1:
          id: 1920
          name: Peach Demo
      description: Account that has been arranged with Peach
      properties:
        id:
          type: integer
          description: unique identifier for an account
          format: int64
          minimum: 1
        name:
          type: string
          description: account name
          minLength: 1
          maxLength: 256
    Campaign:
      title: Campaign
      type: object
      x-examples:
        example-1:
          id: 1000
          name: Pepsi
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        name:
          type: string
          minLength: 1
          maxLength: 256
  securitySchemes:
    API Key - 1:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: ''
          refreshUrl: ''
          scopes: {}
      description: ''
