openapi: 3.0.0
info:
  title: Peach Campaign API
  version: '1.0'
  description: A collection of API to create and distribute campaign across the world
  contact:
    name: API Support
    url: 'https://api.peachvideo.com/support'
    email: api.support@peachvideo.com
servers:
  - url: 'http://localhost:3000'
    description: mock server
tags:
  - name: Account
    description: Account api collection
  - name: Campaign
    description: Campaign api collection
paths:
  /accounts:
    get:
      summary: Retrieve a list of accounts
      tags:
        - Account
      responses:
        '200':
          description: Successful Account Retrieval
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
              examples:
                example-listaccounts:
                  value:
                    - id: 1920
                      name: Peach Demo UK
                    - id: 1921
                      name: Peach Demo Germany
          headers: {}
      operationId: get-accounts
      description: retrieve a list of accounts
      security:
        - Peach Authentication: []
      parameters: []
  '/campaign/{campaignId}':
    get:
      summary: Retrieve campaign by an identifier
      tags:
        - Campaign
      responses:
        '200':
          description: Successful retrieve of a campaign
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Campaign'
              examples:
                example-1:
                  value:
                    id: 1000
                    name: Pepsi
        '404':
          $ref: '#/components/responses/NotFound'
          
      operationId: get-campaign
      description: Retrieve a specific campaign by an identifier
      security:
        - Peach Authentication: []
      parameters: []
    parameters:
      - schema:
          type: integer
          format: int64
          minimum: 1
        name: campaignId
        in: path
        description: Campaign identifier
        required: true
components:
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Account:
      title: Account
      type: object
      x-examples:
        example-1:
          id: 1920
          name: Peach Demo
      description: Account that has been arranged with Peach
      properties:
        id:
          type: integer
          description: unique identifier for an account
          format: int64
          minimum: 1
        name:
          type: string
          description: account name
          minLength: 1
          maxLength: 256
    Campaign:
      title: Campaign
      type: object
      x-examples:
        example-1:
          id: 1000
          name: Pepsi
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        name:
          type: string
          minLength: 1
          maxLength: 256
    Error:
      title: Error
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
  securitySchemes:
    Peach Authentication:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://peach-mock.auth.us-west-2.amazoncognito.com/oauth2/authorize'
          scopes:
            openid: 'JWT Token  that contains claims about the identity of the authenticated user such as name, email, and phone_number'
      description: ''
security:
  - Peach Authentication:
      - openid
